# Generated by Django 5.2.6 on 2025-12-21 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название мероприятия')),
                ('description', models.TextField(help_text='Описание мероприятия')),
                ('organizer', models.ForeignKey(help_text='Организатор этого мероприятия', on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(help_text='Мероприятия, созданные этим организатором', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='Events.event')),
                ('organizer', models.ForeignKey(help_text='Организаторы мероприятий', on_delete=django.db.models.deletion.CASCADE, related_name='organizers', to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(help_text='Зарегестрированные участники', on_delete=django.db.models.deletion.CASCADE, related_name='patricipants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='participant',
            field=models.ManyToManyField(blank=True, help_text='Мероприятие, в котором участвует пользователь', related_name='participanting_events', through='Events.Participation', through_fields=('event', 'participant'), to=settings.AUTH_USER_MODEL),
        ),
    ]
